name: 'Scan multi-platform Docker images'
run-name: '${{ github.ref_type }}_${{ github.ref_name }}@${{ github.triggering_actor }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

env:
  DH_REGISTRY: docker.io
  CONTAINER_TAG: initial

jobs:
  scan-on-linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    permissions:
      contents: read
      packages: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Set parameters to GITHUB_ENV'
        shell: bash
        run: |
          echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)" >> ${GITHUB_ENV}
          echo "GITHUB_ENV:"
          cat ${GITHUB_ENV}
      - name: 'Run Trivy scan'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.DH_REGISTRY }}/${{ secrets.DH_USER }}/${{ env.REPOSITORY_NAME }}:${{ env.CONTAINER_TAG }}'
          format: 'json'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          exit-code: '0'
          version: 'latest'
          output: scan-report-${{ matrix.runner }}.json
      - name: 'Store scan report as artifact'
        uses: actions/upload-artifact@main
        with:
          name: scan-report-${{ matrix.runner }}
          path: scan-report-${{ matrix.runner }}.json
          retention-days: 7
          overwrite: true
          compression-level: 0
