name: 'Prepare multi-platform Docker images'
run-name: '${{ github.ref_type }}_${{ github.ref_name }}@${{ github.triggering_actor }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "45 20 * * *"
  workflow_dispatch:
   inputs:
      CONTAINER_TAG:
        description: 'CONTAINER_TAG (text)'
        required: false
        type: string

env:
  GH_REGISTRY: ghcr.io
  DH_REGISTRY: docker.io
  DHI_REGISTRY: dhi.io
  CONTAINER_TAG: initial

jobs:
  docker-build-test-tag-push:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest]
    permissions:
      contents: write
      packages: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Set parameters to GITHUB_ENV'
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ github.event.inputs.CONTAINER_TAG }}" != "" ]]; then
              echo "CONTAINER_TAG=${{ github.event.inputs.CONTAINER_TAG }}" >> ${GITHUB_ENV}
            fi
          fi
          echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2)" >> ${GITHUB_ENV}
          echo "GITHUB_ENV:"
          cat ${GITHUB_ENV}
      - name: 'Set up QEMU (arm64)'
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/arm64
      - name: 'Set up Docker buildx'
        uses: docker/setup-buildx-action@master
        with:
          version: latest
          driver-opts: |
            network=host
            image=moby/buildkit:master
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@master
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
          ecr: false
          logout: true
      - name: 'Login to DockerHub Container Registry'
        uses: docker/login-action@master
        with:
          registry: ${{ env.DH_REGISTRY }}
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
          ecr: false
          logout: true
      - name: 'Login to DockerHub Container Hardened Registry'
        uses: docker/login-action@master
        with:
          registry: ${{ env.DHI_REGISTRY }}
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
          ecr: false
          logout: true
      - name: 'Clean old containers in GitHub Container Registry'
        uses: actions/delete-package-versions@main
        with:
          owner: ${{ github.repository_owner }}
          package-name: ${{ env.REPOSITORY_NAME }}
          package-type: 'container'
          token: ${{ secrets.GH_TOKEN }}
          min-versions-to-keep: 3
      - name: 'Clean old containers in DockerHub Container Registry'
        uses: lostlink/docker-cleanup@main
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_TOKEN }}
          repositories:  ${{ env.REPOSITORY_NAME }}
          sha-retention-days: 15
          dry-run: false
      - name: 'Build, tag and push multi-platforms Docker images to preconfigured container registries'
        uses: docker/build-push-action@master
        with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: false
          no-cache: false
          github-token: ${{ secrets.GH_TOKEN }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_TOKEN }}
          tags: |
            ${{ secrets.DH_USER }}/${{ env.REPOSITORY_NAME }}:${{ env.CONTAINER_TAG }}
            ${{ env.GH_REGISTRY }}/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}:${{ env.CONTAINER_TAG }}
          platforms: linux/amd64,linux/arm64
