name: 'Test multi-platform Docker images'
run-name: '${{ github.ref_type }}_${{ github.ref_name }}@${{ github.triggering_actor }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  test-on-linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    permissions:
      contents: read
      packages: write
    container:
      image: docker.io/developmententity/gemini-cli:initial
      options:
        -v /dev:/dev
        -u root

    steps:
      - name: 'Docker image test'
        shell: bash
        run: |
          echo -ne "GEMINI_CLI_VERSION="
          gemini --version
